{% set version = "1.5.4" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-writexl
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/writexl_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/writexl/writexl_{{ version }}.tar.gz
  sha256: d0574a29ea22bd78785f50c7cd23c6e10036f65321e26d55a694e931467660d3

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib("c") }}          # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib("m2w64_c") }}    # [win]
    - {{ posix }}filesystem      # [win]
    - {{ posix }}make
    - {{ posix }}sed             # [win]
    - {{ posix }}coreutils       # [win]
    - {{ posix }}zip             # [win]
  host:
    - r-base
    - zlib
  run:
    - r-base

test:
  commands:
    - $R -e "library('writexl')"           # [not win]
    - "\"%R%\" -e \"library('writexl')\""  # [win]

about:
  home: https://libxlsxwriter.github.io
  dev_url: https://github.com/ropensci/writexl
  doc_url: https://docs.ropensci.org/writexl/
  license: BSD-2-Clause
  summary: Zero-dependency data frame to xlsx exporter based on 'libxlsxwriter'.  Fast and no Java or Excel required.
  license_family: BSD
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/BSD_2_clause
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
