appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: kd6hyEQSUZrMMRkCi7tYr2pzWWK26SO+oXBHGd36lgb/JSDLSJa34JjVCAQZ0Cu+dTjTUzLE7WeeL2fP5rX59mH5Sm73LTeI2/08lP82SlENsVmTSZ4Za8GDKfK0Q7dAqdUsIZG0ZiCAEidpsz7ntWswXjAL1G6cXI36ZUC9K92MkoxgGqTVKJH+uWi/I96cVXRkfKS7ylJjez2jalIXdM4QV4bpu0EN1Y6ZrmlCL9Jgf4S9fxRAae1Wx1MDy/I+7gz95nehuZ5wTWYy9SMp3mykiAcM3HiXK5oo8yRAZJ33oVQImwi/UBaL3/021cpezUJxHTEaxal8MtcOB1aO7IAGsRfJoG+b6ERzRl3eVcwwRPiN/tVaZ6AGFICuoxnt+fjNlVqV+9H1jWA38Ei3mlYJ783RFIIUNyc+WT3Zb4nziuxs+LB8Xgd4OwY7YKOgmOGNGFgOo+jyZhaT3zRl9VhcnVcgsmfubjANW1J/Yg6O6YXmD9hYTuD/wiZ0/q/zyAO51YFreNPOddlMKjnkC4OVlvW2BA9dLw1sDD5nweCe0MAJmMe+IhjcMXbqeDyhGLlKhJd8ZPkVQmY/kZnfuQX+wNLtGPIUiZd0WSZKYVyqa6n48duT9fygteBIHUB0GMKyi75MPtGhIOxkFZzjlI0JMn0Lak0QdmOlLBbKXGU=
conda_forge_output_validation: false
